Repository GoogleCloudPlatform/gcp-service-broker, pull requests merged in 2019-09, with the labels that each got.

#527 Cleanup IAM policy when deleting a service account
  pkg/providers/builtin/account_managers/iam.go
  pkg/providers/builtin/account_managers/iam_test.go
  pkg/providers/builtin/account_managers/service_account_manager.go
Labels: cla: yes

#535 Fix Redis
  Gopkg.lock
  docs/classes/google-memorystore-redis.md
  docs/use.md
  pkg/providers/builtin/base/mixins.go
  pkg/providers/builtin/base/peered_network_service.go
  pkg/providers/builtin/base/variables.go
  pkg/providers/builtin/filestore/broker.go
  pkg/providers/builtin/redis/broker.go
  pkg/providers/builtin/redis/definition.go
  pkg/providers/builtin/registry.go
  pkg/providers/builtin/registry_test.go
Labels: bug, cla: yes, cleanup

#537 fix reading tile environment
  pkg/broker/broker_test.go
  pkg/broker/service_definition.go
Labels: bug, cla: yes
