Repository GoogleCloudPlatform/gcp-service-broker, pull requests merged in 2019-06, with the labels that each got.

#471 add ability to run exactly one example by name
  cmd/client.go
  pkg/brokerpak/cmd.go
  pkg/client/example-runner.go
Labels: enhancement

#473 Feature/delete storage objects
  pkg/providers/builtin/storage/broker.go
  pkg/providers/builtin/storage/definition.go
Labels: enhancement

#472 delete replicas if they exist, fixes #466
  pkg/providers/builtin/cloudsql/broker.go
  pkg/providers/builtin/cloudsql/broker_test.go
  pkg/providers/builtin/cloudsql/mysql-definition.go
  pkg/providers/builtin/cloudsql/sql_account_manager.go
Labels: bug

#477 Add support for Memorystore for Redis
  .gitignore
  pkg/providers/builtin/redis/broker.go
  pkg/providers/builtin/redis/definition.go
  pkg/providers/builtin/registry.go
Labels: cla: yes

#480 Document how to create a built-in service
  docs/add-builtin-service.md
Labels: cla: yes, documentation
