Repository GoogleCloudPlatform/gcp-service-broker, pull requests merged in 2019-07, with the labels that each got.

#481 Use VCAP_SERVICES to get the MySQL database
  db_service/setup_db.go
  db_service/vcap.go
  db_service/vcap_test.go
Labels: cla: yes

#476 Migrate column request_detail to datatype text
  db_service/migrations.go
  db_service/models/historical_db.go
Labels: cla: yes

#485 Refactor RunExample to run self-contained examples
  pkg/client/example-runner.go
  pkg/client/example-runner_test.go
Labels: cla: yes

#487 Add command line flag to enable running examples from file name
  cmd/client.go
  pkg/broker/service_definition.go
  pkg/broker/variables.go
  pkg/client/example-runner.go
  pkg/client/example-runner_test.go
  pkg/client/testdata/complete-service-examples-testfile.json
Labels: cla: yes

#488 Fix build process
  .dockerignore
  .travis.yml
  Dockerfile
  pkg/broker/broker_test.go
  pkg/providers/builtin/registry_test.go
Labels: cla: yes

#490 remove broken go report card
  README.md
Labels: cla: yes

#491 Release v4.2.3
  CHANGELOG.md
  OSDF-4.2.3.txt
  docs/customization.md
  docs/use.md
  manifest.yml
  pkg/generator/pcf-artifacts.go
  pkg/providers/builtin/registry_test.go
  pkg/providers/builtin/stackdriver/debugger_definition.go
  pkg/providers/builtin/stackdriver/trace_definition.go
  tile.yml
Labels: cla: yes

#493 generate the brokerpak name based on its version and manifest name
  pkg/brokerpak/cmd.go
Labels: cla: yes, cleanup

#495 Add /tmp folder to Dockerfile
  Dockerfile
Labels: cla: yes

#494 create hack and bump go version
  docs/customization.md
  docs/use.md
  hack/build.sh
  hack/test.sh
  manifest.yml
  pkg/generator/pcf-artifacts.go
  tile.yml
Labels: cla: yes, enhancement

#496 Feature/load builtin brokerpaks
  docs/customization.md
  pkg/brokerpak/config.go
  pkg/brokerpak/config_test.go
  pkg/brokerpak/registrar.go
  pkg/brokerpak/testdata/dummy-brokerpaks/first.brokerpak
  pkg/brokerpak/testdata/dummy-brokerpaks/not-a-brokerpak
  pkg/brokerpak/testdata/dummy-brokerpaks/second.brokerpak
  pkg/brokerpak/testdata/no-brokerpaks/not-a-brokerpak
  tile.yml
Labels: cla: yes, enhancement

#498 added serve-docs command
  cmd/serve.go
Labels: cla: yes, feature

#499 Add environment variables for port
  Dockerfile
Labels: cla: yes
