Repository GoogleCloudPlatform/gcp-service-broker, pull requests merged in 2019-08, with the labels that each got.

#502 Add new /examples endpoint that returns array of CompleteServiceExamples
  cmd/serve.go
  pkg/server/examples.go
  pkg/server/examples_test.go
Labels: cla: yes

#503 Refactor code in client to fetch examples from the server endpoint
  cmd/client.go
  pkg/brokerpak/cmd.go
  pkg/client/example-runner.go
  pkg/client/example-runner_test.go
  pkg/server/examples.go
  pkg/server/examples_test.go
Labels: cla: yes

#504 Remove bad fields
  manifest.yml
  pkg/generator/pcf-artifacts.go
  tile.yml
Labels: bug, cla: yes

#505 pull in plan override capability from develop
  CHANGELOG.md
  brokerapi/brokers/gcp_service_broker.go
  docs/brokerpak-specification.md
  docs/customization.md
  docs/use.md
  pkg/broker/broker_test.go
  pkg/broker/catalog.go
  pkg/broker/service_definition.go
  pkg/generator/customization-md.go
  pkg/generator/types.go
  pkg/providers/tf/definition.go
Labels: cla: yes

#506 cherrypick qol improvements from #439
  CHANGELOG.md
  pkg/brokerpak/manifest.go
Labels: cla: yes, cleanup, documentation, enhancement

#507 cherrypick #442 to master
  CHANGELOG.md
  docs/brokerpak-specification.md
  pkg/broker/broker_test.go
  pkg/broker/service_definition.go
  pkg/providers/tf/definition.go
  pkg/providers/tf/definition_test.go
Labels: cla: yes, enhancement

#511 cherrypick #443 to master
  docs/brokerpak-specification.md
  pkg/varcontext/interpolation/eval_test.go
  pkg/varcontext/interpolation/funcs.go
Labels: cla: yes, enhancement

#512 Tolerate an empty json hash for VCAP_SERVICES
  db_service/vcap.go
Labels: cla: yes

#510 Add migration to modify column type
  CHANGELOG.md
  db_service/migrations.go
Labels: cla: yes

#509 Fix cloudsql user deletion and error handling
  CHANGELOG.md
  pkg/providers/builtin/cloudsql/broker.go
  pkg/providers/builtin/cloudsql/sql_account_manager.go
Labels: cla: yes

#516 cherrypicked helm
  deployments/helm/gcp-service-broker/.gitignore
  deployments/helm/gcp-service-broker/.helmignore
  deployments/helm/gcp-service-broker/Chart.yaml
  deployments/helm/gcp-service-broker/README.md
  deployments/helm/gcp-service-broker/cf-tutorial.md
  deployments/helm/gcp-service-broker/requirements.lock
  deployments/helm/gcp-service-broker/requirements.yaml
  deployments/helm/gcp-service-broker/templates/NOTES.txt
  deployments/helm/gcp-service-broker/templates/_helpers.tpl
  deployments/helm/gcp-service-broker/templates/clusterservicebroker.yaml
  deployments/helm/gcp-service-broker/templates/deployment.yaml
  deployments/helm/gcp-service-broker/templates/ingress.yaml
  deployments/helm/gcp-service-broker/templates/secrets.yaml
  deployments/helm/gcp-service-broker/templates/service.yaml
  deployments/helm/gcp-service-broker/templates/tests/test-connection.yaml
  deployments/helm/gcp-service-broker/values.yaml
Labels: cla: yes

#518 ci: add README.md
  ci/README.md
Labels: cla: yes

#519 disabled redis
  docs/customization.md
  docs/use.md
  pkg/providers/builtin/registry.go
  pkg/providers/builtin/registry_test.go
  tile.yml
Labels: cla: yes

#521 Add option to generate service classes doc into separate file
  ci/tasks/metadata.sh
  cmd/generate.go
  docs/classes/google-bigquery.md
  docs/classes/google-bigtable.md
  docs/classes/google-cloudsql-mysql.md
  docs/classes/google-cloudsql-postgres.md
  docs/classes/google-dataflow.md
  docs/classes/google-datastore.md
  docs/classes/google-dialogflow.md
  docs/classes/google-firestore.md
  docs/classes/google-ml-apis.md
  docs/classes/google-pubsub.md
  docs/classes/google-spanner.md
  docs/classes/google-stackdriver-debugger.md
  docs/classes/google-stackdriver-monitoring.md
  docs/classes/google-stackdriver-profiler.md
  docs/classes/google-stackdriver-trace.md
  docs/classes/google-storage.md
  docs/releasing.md
  docs/use.md
  hack/build.sh
  pkg/generator/types.go
Labels: cla: yes
